### ISSUE TITLE
implementation suggestions

### ISSUE THREAD

**Issue by parf** [lodash-php/lodash-php#2]
**suggestion 1:**
implement all functions as `\lodash\_` class static methods
this way _ class will be loaded on-demand only.
so far php missing namespaced functions on-demand autoload mechanics

```
use lodash\_;

_::$method();
```

**suggestion 2:**
 split class in two or more parts:
 
- first  part - standalone methods
- second part  dependent extensions: (defined in separate composer module)

implement
```
public static function  __callStatic($method, $args) {
    foreach (static::$KNOWN_EXTENSIONS as $ext)
        if (class_exists($ext) && method_exists($ext, $method)) 
           return $ext::$method(...$args);
 }
```

**Comment by pierredup** [comment]
All the functions are already available as part of the `_` class

```
use _;

_::each();
```

The part that is missing is the autoloading of the `_` class, which can definitely be improved (currently the class is always loaded, but that can be part of improving the autoloading in #1)

I don't quite understand what you mean with the dependant extensions in the second suggestion. Can you perhaps explain a bit more?

**Comment by parf** [comment]
90%+ of lodash functions are standalone (do not requires any other composer packages)

My idea is to split package into two - standalone part and part with dependencies.
lodash and lodash-ext
with `__callStatic` trick you can make your "_" class smart, it will automatically use second package methods when it installed

**Comment by pierredup** [comment]
Actually, quite a lot of the functions have a dependency on `symfony/property-access`, which means they aren't really standalone.

I also wouldn't split the package based on composer dependencies. It will make things harder to maintain, as you need to change the packages then each time a new dependency is introduced, and whether a function depends on another package is irrelevant IMO.

I would rather split the package by category so that you can include only a specific set of functions instead of including all of them (E.G `lodash-php/array`, `lodash-php/collection` etc)

**Comment by pierredup** [comment]
Closing this as there isn't anything to do here
