### ISSUE TITLE
Cannot redeclare __()

### ISSUE THREAD

**Issue by matbrady** [lodash-php/lodash-php#22]
I encountered this error after installing this library within a [Bedrock/Sage](https://roots.io/) WordPress application. This issue seems to be similar to #12.

### Error
```
Fatal error: Cannot redeclare __() (previously declared in /app/vendor/lodash-php/lodash-php/src/compiled.php:5) in /app/web/wp/wp-includes/l10n.php on line 249
```

### Conflicting File
[**I10n.php**](https://github.com/WordPress/WordPress/blob/master/wp-includes/l10n.php#L242-L256)
```php
/**
 * Retrieve the translation of $text.
 *
 * If there is no translation, or the text domain isn't loaded, the original text is returned.
 *
 * @since 2.1.0
 *
 * @param string $text   Text to translate.
 * @param string $domain Optional. Text domain. Unique identifier for retrieving translated strings.
 *                       Default 'default'.
 * @return string Translated text.
 */
function __( $text, $domain = 'default' ) {
	return translate( $text, $domain );
}
```

**Comment by pierredup** [comment]
Thanks for the report. Currently, Lodash-php only defines the `__` function if it doesn't exist. In your situation, Lodash-php is loaded first, which means the `__` function does not exist and is then defined. The `I10n.php` in your example is loaded after Lodash, which then also tries to define the `__` function but fails since it already exists. So there isn't anything that can be done from this project's perspective.

**Comment by matbrady** [comment]
@pierredup Thanks for the quick reply! 👍Your response makes sense. I'll look into altering the loading order.

**Comment by Youdaman** [comment]
Hey @matbrady did you manage to alter the loading order? I'm having the same issue with lodash conflicting with WP's I10n.php
