### ISSUE TITLE
Can I use this without Composer?

### ISSUE THREAD

**Issue by thorst** [lodash-php/lodash-php#24]
Id like to just use the old school require statements, and download the zip here. 

Is that possible?

**Comment by pierredup** [comment]
@thorst While technically, it is possible, it is not recommended as it will be a lot harder to include all the dependencies.

For example, this project uses the `symfony/property-access` package, so you will need to manually include that with all the relevant files in your project.

Also, you will need to include the entire library at once, as there are a lot of internal functions split over multiple files, so if you only include, for example, the file `src/Collection/map.php`, it won't just work out of the box since you need to require the internal functions as well.
